CREATE TABLE IF NOT EXISTS `user_info` (
  `id`          INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user`        VARCHAR(30) ,
  `application` VARCHAR(30) ,
  `time`        DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;