// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addUser": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Add permission for a user to apply auth token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Add permission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the email address of the user",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the application which user used to",
                        "name": "app",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth": {
            "post": {
                "description": "Apply a authrization token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Apply a authrization token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email address",
                        "name": "user",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "application name",
                        "name": "app",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "if send token to email, default false",
                        "name": "send",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "token expiry date, unit hours. Maximum: 72, default 24 hours.",
                        "name": "expiration",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/call": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Send an expedited call by feishu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Send"
                ],
                "summary": "Send an expedited call",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email address",
                        "name": "receiver",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "message content",
                        "name": "message",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "times of call, default 0",
                        "name": "retry",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "repeat call interval, unit minutes, default 10 minutes",
                        "name": "interval",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/email": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Send a message to a specify email address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Send"
                ],
                "summary": "Send message by email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email address",
                        "name": "receiver",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "email subject",
                        "name": "subject",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "email message",
                        "name": "message",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "email content format, text or html, default text",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/feishu": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Send a message to a feishu receiver by feishu bot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Send"
                ],
                "summary": "Send a message to feishu receiver",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email address",
                        "name": "receiver",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "message content",
                        "name": "message",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/group": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Send a message to a feishu group by feishu bot webhook",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Send"
                ],
                "summary": "Send message by feishu bot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "feishu chatbot webhook",
                        "name": "receiver",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "message content",
                        "name": "message",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/list": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "List all message template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Template"
                ],
                "summary": "List message template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/messagestatus": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Check if the latest message has been read",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Check"
                ],
                "summary": "Check if message has been read",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email address",
                        "name": "receiver",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "message content",
                        "name": "message",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "message id",
                        "name": "message_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Time range for querying history messages, unit hours, default 10 hours ",
                        "name": "interval",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pagerduty": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Use Pagerduty to call a person who",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Send"
                ],
                "summary": "Use Pagerduty to call",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the summary of the alert",
                        "name": "summary",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the source of the alert",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "the severity of the alert",
                        "name": "severity",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the details of the alert",
                        "name": "details",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Refresh Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh Token",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "token expiry date, unit hours. Maximum: 72, default 24 hours.",
                        "name": "expiration",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "if send token to email, default false",
                        "name": "send",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/sms": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Send a message to a phone number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Send"
                ],
                "summary": "Send message by sms",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Message Template Id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Message Template Name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Message Params, separated by '|'",
                        "name": "params",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Receiver phone number, area code required",
                        "name": "receiver",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Notification API",
	Description:      "This API is used to send notification.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
