basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This API is used to send notification.
  title: Notificcation API
  version: "1.0"
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Apply a authrization token
      parameters:
      - description: Use the zilliz email
        in: query
        name: user
        required: true
        type: string
      - description: application name
        in: query
        name: app
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Apply a authrization token
      tags:
      - Auth
  /email:
    post:
      consumes:
      - application/json
      description: Send a message to a specify email address
      parameters:
      - description: email address
        in: query
        name: receiver
        required: true
        type: string
      - description: email subject
        in: query
        name: subject
        required: true
        type: string
      - description: email message
        in: query
        name: message
        required: true
        type: string
      - description: email content format, text or html, default text
        in: query
        name: format
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Send message by email
      tags:
      - Send
  /feishu:
    post:
      consumes:
      - application/json
      description: Send a message to feishu
      parameters:
      - description: email address
        in: query
        name: receiver
        required: true
        type: string
      - description: email message
        in: query
        name: message
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Send message by feishu
      tags:
      - Send
  /list:
    get:
      consumes:
      - application/json
      description: List all message template
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: List message template
      tags:
      - Template
  /refresh:
    get:
      consumes:
      - application/json
      description: Refresh Token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Refresh Token
      tags:
      - Auth
  /sms:
    post:
      consumes:
      - application/json
      description: Send a message to a phonenumber
      parameters:
      - description: Message Template Id
        in: query
        name: id
        type: integer
      - description: Message Template Name
        in: query
        name: name
        type: string
      - description: Message Params
        in: query
        name: params
        type: string
      - description: Receiver phone number, area code required
        in: query
        name: receiver
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Send message by sms
      tags:
      - Send
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
