basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This API is used to send notification.
  title: Notificcation API
  version: "1.0"
paths:
  /add:
    post:
      consumes:
      - application/json
      description: Add a message template to db
      parameters:
      - description: message template name
        in: query
        name: name
        required: true
        type: string
      - description: message template
        in: query
        name: message
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Regist message template
      tags:
      - Template
  /auth:
    post:
      consumes:
      - application/json
      description: Apply a authrization token
      parameters:
      - description: Use the zilliz email
        in: query
        name: user
        required: true
        type: string
      - description: application name
        in: query
        name: app
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Apply a authrization token
      tags:
      - Auth
  /list:
    get:
      consumes:
      - application/json
      description: List all message template
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: List message template
      tags:
      - Template
  /refresh:
    get:
      consumes:
      - application/json
      description: Refresh Token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Refresh Token
      tags:
      - Auth
  /send:
    post:
      consumes:
      - application/json
      description: Send notification to a specify receiver
      parameters:
      - description: Message Template Id
        in: query
        name: id
        type: integer
      - description: Message Template Name
        in: query
        name: name
        type: string
      - description: Message Params
        in: query
        name: params
        type: string
      - description: email subject
        in: query
        name: subject
        type: string
      - description: ReceiverType
        in: query
        name: receivertype
        required: true
        type: string
      - description: Receiver
        in: query
        name: receiver
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - Bearer: []
      summary: Send notification
      tags:
      - Send
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
